name: CI

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      # https://github.com/TriPSs/conventional-changelog-action
      - name: Generate changelog and git tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: "chore(release): {version}\n\n[skip ci]"
          skip-ci: false
          git-user-name: github-actions[bot]
          git-user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          tag-prefix: ""
          version-file: pyproject.toml
          version-path: tool.poetry.version
          create-summary: true
          config-file-path: .github/changelog-config.js
          # TODO: add header # Changelog to file.

      # - name: Create GitHub release
      #   uses: actions/create-release@v1
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   with:
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
